// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-products.ts
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "List inventory products for the signed-in user, optionally filtered by a name/SKU/barcode search term or by low stock.",
  inputSchema: {
    search: z.string().optional().describe("Case-insensitive match on product name."),
    category: z.string().optional().describe("Filter by product category."),
    lowStockOnly: z.boolean().optional().describe("Only return products at or below their minimum stock level."),
    limit: z.number().int().min(1).max(200).optional().describe("Maximum rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, category, lowStockOnly, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("products").select("id,name,sku,barcode,category,price,stock,min_stock,unit,is_active,expiry_date").order("name", { ascending: true }).limit(limit ?? 50);
    if (search) query = query.ilike("name", `%${search}%`);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (lowStockOnly ? (data ?? []).filter((p) => Number(p.stock) <= Number(p.min_stock)) : data) ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, products: rows }
    };
  }
});

// src/lib/mcp/tools/update-product-stock.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var update_product_stock_default = defineTool2({
  name: "update_product_stock",
  title: "Update product stock",
  description: "Set or adjust the stock quantity of one product owned by the signed-in user. Use `mode: 'adjust'` to add/subtract, `mode: 'set'` to overwrite.",
  inputSchema: {
    productId: z2.string().describe("The product's id."),
    quantity: z2.number().describe("Quantity to set, or the delta when adjusting (may be negative)."),
    mode: z2.enum(["set", "adjust"]).optional().describe("Defaults to 'adjust'.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ productId, quantity, mode }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: existing, error: readError } = await supabase.from("products").select("id,name,stock").eq("id", productId).maybeSingle();
    if (readError) return { content: [{ type: "text", text: readError.message }], isError: true };
    if (!existing) return { content: [{ type: "text", text: `No product found with id ${productId}` }], isError: true };
    const nextStock = (mode ?? "adjust") === "set" ? quantity : Number(existing.stock) + quantity;
    if (nextStock < 0) {
      return { content: [{ type: "text", text: "Resulting stock would be negative." }], isError: true };
    }
    const { data, error } = await supabase.from("products").update({ stock: nextStock, updated_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("id", productId).select("id,name,stock").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `${data?.name}: stock is now ${data?.stock}` }],
      structuredContent: { product: data }
    };
  }
});

// src/lib/mcp/tools/list-orders.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_orders_default = defineTool3({
  name: "list_orders",
  title: "List orders",
  description: "List recent sales orders for the signed-in user, newest first, optionally filtered by status or date range.",
  inputSchema: {
    status: z3.string().optional().describe("Filter by order_status, e.g. 'completed' or 'pending'."),
    fromDate: z3.string().optional().describe("ISO date; only orders on or after this date."),
    toDate: z3.string().optional().describe("ISO date; only orders on or before this date."),
    limit: z3.number().int().min(1).max(200).optional().describe("Maximum rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, fromDate, toDate, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("orders").select("id,order_date,customer_name,customer_phone,items,subtotal,gst,total,payment_method,payment_status,order_status").order("order_date", { ascending: false }).limit(limit ?? 25);
    if (status) query = query.eq("order_status", status);
    if (fromDate) query = query.gte("order_date", fromDate);
    if (toDate) query = query.lte("order_date", toDate);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-customers.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_customers_default = defineTool4({
  name: "list_customers",
  title: "List customers",
  description: "List or search customers of the signed-in user, including contact details and lifetime spend.",
  inputSchema: {
    search: z4.string().optional().describe("Case-insensitive match on customer name."),
    limit: z4.number().int().min(1).max(200).optional().describe("Maximum rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("customers").select("id,name,phone,email,address,city,state,status,total_orders,total_spent,last_order_date").order("total_spent", { ascending: false }).limit(limit ?? 25);
    if (search) query = query.ilike("name", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, customers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/sales-summary.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var sales_summary_default = defineTool5({
  name: "sales_summary",
  title: "Sales summary",
  description: "Summarise sales totals, order count and top-selling products for the signed-in user over a date range.",
  inputSchema: {
    fromDate: z5.string().optional().describe("ISO date; defaults to 30 days ago."),
    toDate: z5.string().optional().describe("ISO date; defaults to now.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ fromDate, toDate }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const from = fromDate ?? new Date(Date.now() - 30 * 24 * 60 * 60 * 1e3).toISOString();
    const to = toDate ?? (/* @__PURE__ */ new Date()).toISOString();
    const { data, error } = await supabase.from("orders").select("total,items,order_date").gte("order_date", from).lte("order_date", to);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const orders = data ?? [];
    const revenue = orders.reduce((sum, o) => sum + Number(o.total ?? 0), 0);
    const productTotals = /* @__PURE__ */ new Map();
    for (const order of orders) {
      const items = Array.isArray(order.items) ? order.items : [];
      for (const item of items) {
        const name = String(item.name ?? "Unknown");
        const quantity = Number(item.quantity ?? 0);
        const price = Number(item.price ?? 0);
        const entry = productTotals.get(name) ?? { quantity: 0, revenue: 0 };
        entry.quantity += quantity;
        entry.revenue += quantity * price;
        productTotals.set(name, entry);
      }
    }
    const topProducts = [...productTotals.entries()].map(([name, stats]) => ({ name, ...stats })).sort((a, b) => b.revenue - a.revenue).slice(0, 10);
    const summary = {
      from,
      to,
      orderCount: orders.length,
      revenue: Number(revenue.toFixed(2)),
      averageOrderValue: orders.length ? Number((revenue / orders.length).toFixed(2)) : 0,
      topProducts
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "dlzfgzyrmttfoimevnxb";
var mcp_default = defineMcp({
  name: "kothari-smart-inventory-suite",
  title: "Kothari-smart-inventory-suite",
  version: "0.1.0",
  instructions: "Tools for the Kothari smart inventory suite: inspect products and stock levels, adjust stock, review orders and customers, and summarise sales. All data is scoped to the signed-in user's account.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_products_default,
    update_product_stock_default,
    list_orders_default,
    list_customers_default,
    sales_summary_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
