// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsnozsletuytigsrmzvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzbm96c2xldHV5dGlnc3JtenZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNDIwNjAsImV4cCI6MjA3NDcxODA2MH0.JFgN1JjA_oKp50kvRQZyZx5WbWRrtiCtJ2qm--ajSrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});