// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbosbuxieeenoavlnbyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxib3NidXhpZWVlbm9hdmxuYnlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MjUxNTMsImV4cCI6MjA2ODUwMTE1M30.3Ioz2RZEe6vESt7oTEzFexZEhu1SRxuAOqrWLu0422k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});