// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlmococtgqyuczimomgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsbW9jb2N0Z3F5dWN6aW1vbWd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTE3MjAsImV4cCI6MjA2OTI4NzcyMH0.GxkNd44pH_vBYhYcDd93PMfaUXkzMe68YPHqhhHkf7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});